### ISSUE TITLE
out of date

### ISSUE THREAD

**Issue by banesullivan** [conda-forge/pyvista-feedstock#29]
this isn't automatically updating from our last few releases that shipped to PyPI.

**Comment by banesullivan** [comment]
@conda-forge/core, could you all please help?

**Comment by beckermr** [comment]
Did you make sure to ship source distributions?

**Comment by beckermr** [comment]
Yup. You only uploaded wheels.

**Comment by banesullivan** [comment]
Ahhh, we didn't realize this would be an issue when making the switch.

pinging @akaszynski, looks like we need to adjust the deploy process

**Comment by akaszynski** [comment]
We'll have to ship both then.  Didn't realize this was an issue!

**Comment by akaszynski** [comment]
Uploaded to https://pypi.org/manage/project/pyvista/release/0.25.3/

Updating the build shortly...

**Comment by marcelotrevisani** [comment]
> We'll have to ship both then. Didn't realize this was an issue!

other packaging systems also use the sdist package on ``pypi``, such as debian, anaconda, etc
It is important to always upload the sdist package as well :)
