### ISSUE TITLE
not updating from dist on pypi

### ISSUE THREAD

**Issue by banesullivan** [conda-forge/pyvista-feedstock#33]
@conda-forge/core, can you all help us figure out what's going on? We have had two releases to PyPI that have not registered here

**Comment by banesullivan** [comment]
https://pypi.org/project/pyvista/#history

And note the source distribution tarball is present https://pypi.org/project/pyvista/#files

**Comment by wolfv** [comment]
The bot was down. Should be back online now!

**Comment by mbargull** [comment]
This isn't an issue with this feedstock but just that the bot has been down a couple of days: https://conda-forge.org/status/#incident_history
Please monitor https://conda-forge.org/status/#repos_and_bots to see when it should be fully operational again. Until then, you can issue PRs manually, of course.

**Comment by banesullivan** [comment]
Ah thank you all!
