### ISSUE TITLE
import broken with vtk 9.0.1

### ISSUE THREAD

**Issue by Keou0007** [conda-forge/pyvista-feedstock#41]
see [here](https://github.com/conda-forge/vtk-feedstock/issues/144)

import fails with vtk version 9.0.1
This needs to be fixed either in vtk or in the vtk feedstock, but in the meantime I suggest forcing vtk version in pyvista conda recipe. 

9.0. seems to work, but perhaps ~=8 would be safer?

**Comment by Keou0007** [comment]
I've done some digging and found at this this occurs due to mismatch in packages if condarc channels are set as -defaults and -conda-forge in that priority order.
libhogweed comes from the package nettle and nettle has version 3.4.1 available in pkgs/main and 3.7 available in conda-forge. clearly something in vtk 9.0.1 requires a newer version of nettle.

setting a dependency requirement of nettle >= 3.7 should resolve this and force conda to get the conda-forge version of nettle when it installs the conda-forge version of vtk, if default channels are prioritised.

**Comment by banesullivan** [comment]
@Keou0007, would you be able to make a PR for this in the recipe?

**Comment by Keou0007** [comment]
Oooo. I’ve never made a recipe. If you’re not in a rush, I can figure out how it works. Sure.

**Comment by banesullivan** [comment]
No need to make a recipe. All we need to change is the `nettle >= 3.7` depend, right? If so, we just add that to the recipe and bump the build number

**Comment by Keou0007** [comment]
My point is I would need to figure out where to make the change. I can do it, but I have other things on today. I’ll look at it tomorrow, or maybe later tonight.
